const komplett = {
    name: "KOMPLETT",
    selectors: {
        title: ".product-main-info-webtext1",
        price: ".product-price-now",
        stock: ".stockstatus-stock-details"
    },
    cards: [
        "https://www.komplett.se/product/1174400/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3070-phantom",
        "https://www.komplett.se/product/1174397/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3070-phantom-gs",
        "https://www.komplett.se/product/1168375/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3070-ventus-3x-oc",
        "https://www.komplett.se/product/1168415/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-eagle-oc",
        "https://www.komplett.se/product/1171368/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3070-eagle",
        "https://www.komplett.se/product/1173939/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3070-aorus-master",
        "https://www.komplett.se/product/1174509/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3060-ti-aorus-master",
        "https://www.komplett.se/product/1176459/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3070-amp-holo",
        "https://www.komplett.se/product/1177553/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3070-jetstream-oc",
        "https://www.komplett.se/product/1171801/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3080-phantom-gs",
        "https://www.komplett.se/product/1168752/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3070-dual",
        "https://www.komplett.se/product/1171798/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3080-phantom",
        "https://www.komplett.se/product/1172252/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3070-gamingpro-oc",
        "https://www.komplett.se/product/1173669/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3080-suprim-x",
        "https://www.komplett.se/product/1173938/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3070-vision-oc",
        "https://www.komplett.se/product/1174190/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3070-suprim-x",
        "https://www.komplett.se/product/1174392/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3060-ti-phoenix-gs",
        "https://www.komplett.se/product/1174206/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3060-ti-tuf-gaming-oc",
        "https://www.komplett.se/product/1168418/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-aorus-master",
        "https://www.komplett.se/product/1174511/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3060-ti-gaming-oc",
        "https://www.komplett.se/product/1168398/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3080-trinity",
        "https://www.komplett.se/product/1174275/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3060-ti-twin-edge-oc",
        "https://www.komplett.se/product/1174403/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3060-ti-ghost-oc",
        "https://www.komplett.se/product/1174508/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3060-ti-eagle-oc",
        "https://www.komplett.se/product/1168419/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-gaming-oc",
        "https://www.komplett.se/product/1171367/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3070-eagle-oc",
        "https://www.komplett.se/product/1171562/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-vision-oc",
        "https://www.komplett.se/product/1170425/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3080-amp-holo",
        "https://www.komplett.se/product/1168376/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3070-ventus-2x-oc",
        "https://www.komplett.se/product/1168399/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3070-twin-edge",
        "https://www.komplett.se/product/1174211/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3060-ti-dual-oc",
        "https://www.komplett.se/product/1174276/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3060-ti-twin-edge",
        "https://www.komplett.se/product/1168380/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3080-gaming-x-trio",
        "https://www.komplett.se/product/1174401/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3060-ti-dual",
        "https://www.komplett.se/product/1168358/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3080-tuf-gaming",
        "https://www.komplett.se/product/1171366/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3070-gaming-oc",
        "https://www.komplett.se/product/1168379/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3080-ventus-3x-oc",
        "https://www.komplett.se/product/1168436/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3080-rog-strix-oc",
        "https://www.komplett.se/product/1171385/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3070-tuf-oc",
        "https://www.komplett.se/product/1176557/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3070-ek",
        "https://www.komplett.se/product/1175541/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3060-ti-gaming-x-trio",
        "https://www.komplett.se/product/1177556/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3060-ti-dual-mini-oc",
        "https://www.komplett.se/product/1171796/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3070-phoenix-gs",
        "https://www.komplett.se/product/1174399/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3070-gamerock-oc",
        "https://www.komplett.se/product/1176244/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3070-rog-strix-oc-white",
        "https://www.komplett.se/product/1176247/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3080-rog-strix-oc-white",
        "https://www.komplett.se/product/1176385/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3060-ti-ventus-2x-ocv1",
        "https://www.komplett.se/product/1177557/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3060-ti-dual-mini",
        "https://www.komplett.se/product/1175535/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3060-ti-ventus-3x-oc",
        "https://www.komplett.se/product/1168439/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3080-rog-strix",
        "https://www.komplett.se/product/1174207/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3060-ti-dual",
        "https://www.komplett.se/product/1175718/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-eagle",
        "https://www.komplett.se/product/1177640/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-aorus-gamingbox",
        "https://www.komplett.se/product/1168128/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3080-gamingpro",
        "https://www.komplett.se/product/1168416/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-aorus-xtreme",
        "https://www.komplett.se/product/1168422/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3080-phoenix-gs",
        "https://www.komplett.se/product/1168754/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3070-rog-strix",
        "https://www.komplett.se/product/1170422/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3070-twin-edge-oc",
        "https://www.komplett.se/product/1171797/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3080-gamerock-oc",
        "https://www.komplett.se/product/1174235/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3080-ek",
        "https://www.komplett.se/product/1174394/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3060-ti-dual-oc",
        "https://www.komplett.se/product/1174395/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3060-ti-gamingpro",
        "https://www.komplett.se/product/1174396/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3070-gamerock",
        "https://www.komplett.se/product/1174510/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3060-ti-gaming-oc-pro",
        "https://www.komplett.se/product/1174512/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3060-ti-eagle",
        "https://www.komplett.se/product/1175239/datorutrustning/datorkomponenter/grafikkort/palit-geforce-rtx-3070-jetstream",
        "https://www.komplett.se/product/1175619/datorutrustning/datorkomponenter/grafikkort/zotac-geforce-rtx-3070-twin-edge-oc-white",
        "https://www.komplett.se/product/1175704/datorutrustning/datorkomponenter/grafikkort/gigabyte-geforce-rtx-3080-aorus-xtreme-wf",
        "https://www.komplett.se/product/1176458/datorutrustning/datorkomponenter/grafikkort/msi-geforce-rtx-3070-suprim",
        "https://www.komplett.se/product/1168129/datorutrustning/datorkomponenter/grafikkort/gainward-geforce-rtx-3080-phoenix-10gb",
        "https://www.komplett.se/product/1174209/datorutrustning/datorkomponenter/grafikkort/asus-geforce-rtx-3060-ti-tuf-gaming"
      ]
};

export default komplett;